version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: training_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build: ./app
    container_name: training-app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: training_db
    volumes:
      - ./public-html:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini   # твой кастомный php.ini для app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-container
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"
    volumes:
      - ./phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini